<a href="https://colab.research.google.com/github/gustavohroos/treinamento-h2ia/blob/main/Buscas-SEM-Info/Buscas_sem_informa%C3%A7%C3%A3o.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# O Problema
Sliding Puzzle - Bloco Deslizante

In [5]:
# !wget -qq https://miro.medium.com/max/700/1*W7jg4GmEjGBypd9WPktasQ.gif
from IPython.display import Image
Image(url='https://miro.medium.com/max/700/1*W7jg4GmEjGBypd9WPktasQ.gif',width=200)

# Resolver o quebra-cabeças usando Buscas

In [6]:
import numpy as np
import time
from typing import List, Tuple
from copy import deepcopy
from collections import deque

In [7]:
class Node:

    def __init__(self, puzzle: List[int], parent = None) -> None:
        self.children = []
        self.parent = parent
        self.moves = []
        self.puzzle = np.array(puzzle)

    def __eq__(self, other: object) -> bool:
        return (self.puzzle == other.puzzle).all()
    
    def __repr__(self) -> str:
        return (str(self.puzzle[0]) + '\n' + 
                str(self.puzzle[1]) + '\n' + 
                str(self.puzzle[2]) + '\n')
    
    def expand_node(self):
        
        i, j = np.where(self.puzzle == 0)

        if j > 0: #Moves left
            pc = np.array(deepcopy(self.puzzle))
            pc[i, j-1], pc[i, j] = pc[i, j], pc[i, j-1]
            child = Node(pc)
            self.children.append(child)
            child.parent = self

        if j < 2: #Moves right
            pc = np.array(deepcopy(self.puzzle))
            pc[i, j+1], pc[i, j] = pc[i, j], pc[i, j+1]
            child = Node(pc)
            self.children.append(child)
            child.parent = self
        
        if i > 0: #Moves up
            pc = np.array(deepcopy(self.puzzle))
            pc[i-1, j], pc[i, j] = pc[i, j], pc[i-1, j]
            child = Node(pc)
            self.children.append(child)
            child.parent = self
        
        if i < 2: #Moves down
            pc = np.array(deepcopy(self.puzzle))
            pc[i+1, j], pc[i, j] = pc[i, j], pc[i+1, j]
            child = Node(pc)
            self.children.append(child)
            child.parent = self

    def len(self) -> int:
        return self.children.count()

def path_tracer(node: Node) -> List[Node]:
        current = node
        path = []
        path.append(current)

        while current.parent is not None:
            current = current.parent
            path.append(current)
        
        path.reverse()

        return path

puzzle = [[2,0,3],[8,4,5],[7,6,1]] #Harder
# puzzle = [[1, 2, 3], [4, 0, 6], [7, 5, 8]] #Easier to test

root = Node(puzzle)

## Busca em largura

In [8]:
def BreadthFirstSearch(root: Node) -> List[Node]:
        path = []
        open_list = deque([root])
        closed_list = []
        goal_found = False
        expected = Node([[1, 2, 3], [4, 5, 6], [7, 8, 0]])
        count = 0

        if root == expected:
            goal_found = True

        while open_list and not goal_found:
            current_node = open_list.popleft()
            closed_list.append(current_node)
            
            current_node.expand_node()

            for child in current_node.children:
                if child == expected:
                    
                    goal_found = True
                    path = path_tracer(child)

                if child not in open_list and child not in closed_list:
                    open_list.append(child)
                    count += 1
                    
            
        return path, count

start = time.time()
solution, count = BreadthFirstSearch(root)

if solution:
    print('Goal found.')
    print(f'It takes {count} nodes.')
    for puzzle in solution:
        print(puzzle)
    print(f'Time taken: {(time.time() - start):.4f} seconds.')
else:
    print('No path to solution is found')

Goal found.
It takes 37157 nodes.
[2 0 3]
[8 4 5]
[7 6 1]

[2 4 3]
[8 0 5]
[7 6 1]

[2 4 3]
[0 8 5]
[7 6 1]

[0 4 3]
[2 8 5]
[7 6 1]

[4 0 3]
[2 8 5]
[7 6 1]

[4 3 0]
[2 8 5]
[7 6 1]

[4 3 5]
[2 8 0]
[7 6 1]

[4 3 5]
[2 8 1]
[7 6 0]

[4 3 5]
[2 8 1]
[7 0 6]

[4 3 5]
[2 0 1]
[7 8 6]

[4 3 5]
[2 1 0]
[7 8 6]

[4 3 0]
[2 1 5]
[7 8 6]

[4 0 3]
[2 1 5]
[7 8 6]

[4 1 3]
[2 0 5]
[7 8 6]

[4 1 3]
[0 2 5]
[7 8 6]

[0 1 3]
[4 2 5]
[7 8 6]

[1 0 3]
[4 2 5]
[7 8 6]

[1 2 3]
[4 0 5]
[7 8 6]

[1 2 3]
[4 5 0]
[7 8 6]

[1 2 3]
[4 5 6]
[7 8 0]

Time taken: 2896.6564 seconds.


## Busca em Profundidade

In [9]:
def DepthFirstSearch(root: Node) -> List[Node]:
        path = []
        open_list = deque([root])
        closed_list = []
        goal_found = False
        expected = Node([[1, 2, 3], [4, 5, 6], [7, 8, 0]])
        count = 0

        if root == expected:
            goal_found = True

        while open_list and not goal_found:
            current_node = open_list.pop()
            closed_list.append(current_node)
            
            current_node.expand_node()

            for child in current_node.children:
                if child == expected:
                    path = path_tracer(child)
                    goal_found = True

                if child not in open_list and child not in closed_list:
                    open_list.append(child)
                    count += 1
            
        return path, count

start = time.time()
solution, count = DepthFirstSearch(root)

if solution:
    print('Goal found.')
    print(f'It takes {count} nodes.')
    for puzzle in solution:
        print(puzzle)
    print(f'Time taken: {(time.time() - start):.4f} seconds.')
else:
    print('No path to solution is found')

Streaming output truncated to the last 5000 lines.
[8 5 3]
[1 7 4]

[6 5 2]
[8 0 3]
[1 7 4]

[6 5 2]
[8 7 3]
[1 0 4]

[6 5 2]
[8 7 3]
[1 4 0]

[6 5 2]
[8 7 0]
[1 4 3]

[6 5 0]
[8 7 2]
[1 4 3]

[6 0 5]
[8 7 2]
[1 4 3]

[0 6 5]
[8 7 2]
[1 4 3]

[8 6 5]
[0 7 2]
[1 4 3]

[8 6 5]
[1 7 2]
[0 4 3]

[8 6 5]
[1 7 2]
[4 0 3]

[8 6 5]
[1 0 2]
[4 7 3]

[8 0 5]
[1 6 2]
[4 7 3]

[8 5 0]
[1 6 2]
[4 7 3]

[8 5 2]
[1 6 0]
[4 7 3]

[8 5 2]
[1 6 3]
[4 7 0]

[8 5 2]
[1 6 3]
[4 0 7]

[8 5 2]
[1 0 3]
[4 6 7]

[8 0 2]
[1 5 3]
[4 6 7]

[8 2 0]
[1 5 3]
[4 6 7]

[8 2 3]
[1 5 0]
[4 6 7]

[8 2 3]
[1 5 7]
[4 6 0]

[8 2 3]
[1 5 7]
[4 0 6]

[8 2 3]
[1 0 7]
[4 5 6]

[8 0 3]
[1 2 7]
[4 5 6]

[8 3 0]
[1 2 7]
[4 5 6]

[8 3 7]
[1 2 0]
[4 5 6]

[8 3 7]
[1 2 6]
[4 5 0]

[8 3 7]
[1 2 6]
[4 0 5]

[8 3 7]
[1 0 6]
[4 2 5]

[8 0 7]
[1 3 6]
[4 2 5]

[8 7 0]
[1 3 6]
[4 2 5]

[8 7 6]
[1 3 0]
[4 2 5]

[8 7 6]
[1 3 5]
[4 2 0]

[8 7 6]
[1 3 5]
[4 0 2]

[8 7 6]
[1 0 5]
[4 3 2]

[8 0 6]
[1 7 5]
[4 3 2]

[8 6 0]
[1 7 5]
[4 3 2]

[8 6 5]

## Discorra sobre o desempenho dos métodos em questões de:


1.   Consumo de memória
2.   Processamento

